# This is main Liferay configuration file, common (shared) for all Liferay environments.
#
# Liferay Workspace will copy this file into Liferay bundle's root directory (= ${liferay.home})
# when Liferay bundle is being built.

##
## JDBC
##

#
# MariaDB
#
jdbc.default.driverClassName=org.mariadb.jdbc.Driver
jdbc.default.url=jdbc:mariadb://database/lportal?dontTrackOpenResources=true&characterEncoding=UTF-8&holdResultsOpenOverStatementClose=true&useFastDateParsing=false
jdbc.default.username=dxpcloud

company.default.name=Liferay AC
company.default.web.id=liferay.com
terms.of.use.required=false

##
## Retry JDBC connection on portal startup.
##

#
# Set the number of seconds to retry getting a JDBC connection on portal
# startup.
#
retry.jdbc.on.startup.delay=5
#
# Set the max number of times to retry getting a JDBC connection on portal
# startup.
#
retry.jdbc.on.startup.max.retries=5