#
# Application
#

liferay.marketplace.dxp.auth.client.id=
liferay.marketplace.dxp.auth.client.secret=
liferay.marketplace.koroneiki.auth.token=
liferay.marketplace.koroneiki.auth.url=
liferay.marketplace.provisioning.auth.client.id=
liferay.marketplace.provisioning.auth.client.secret=
liferay.marketplace.provisioning.auth.url=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-spring-boot-oauth-application-user-agent
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081