#
# Application
#

liferay.jethr0.git.branch.archive.cron=0 0 * * * *

liferay.jethr0.github.upstream.branch.urls=\
    https://github.com/liferay/com-liferay-osb-asah-private/tree/7.0.x,\
    https://github.com/liferay/com-liferay-osb-asah-private/tree/4.4.x,\
    https://github.com/liferay/liferay-jenkins-ee/tree/master,\
    https://github.com/liferay/liferay-plugins-ee/tree/7.0.x,\
    https://github.com/liferay/liferay-plugins-ee/tree/ee-6.2.x,\
    https://github.com/liferay/liferay-portal/tree/master,\
    https://github.com/liferay/liferay-portal-ee/tree/7.3.x,\
    https://github.com/liferay/liferay-portal-ee/tree/7.2.x,\
    https://github.com/liferay/liferay-portal-ee/tree/7.1.x,\
    https://github.com/liferay/liferay-portal-ee/tree/7.0.x,\
    https://github.com/liferay/liferay-portal-ee/tree/ee-6.2.x,\
    https://github.com/liferay/liferay-portal-ee/tree/ee-6.1.x

liferay.jethr0.headless.server.oauth.application.external.reference.code=liferay-jethr0-etc-spring-boot-oauth-application-headless-server
liferay.jethr0.jenkins.queue.update.cron=0 */5 * * * *
liferay.jethr0.job.archive.cron=0 0 * * * *
liferay.jethr0.job.queue.update.cron=0 */5 * * * *
liferay.jethr0.job.prioritizer=Default Job Prioritizer

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    ${liferay.jethr0.headless.server.oauth.application.external.reference.code},\
    liferay-jethr0-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

spring.jms.listener.auto-startup=false
server.port=58081