/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

module.exports = {
	build: {
		exports: [
			'incremental-dom',
			{name: 'incremental-dom-string', symbols: 'auto'},
			{name: 'metal', symbols: 'auto'},
			'metal-affix',
			'metal-ajax',
			'metal-anim',
			'metal-aop',
			'metal-assertions',
			'metal-clipboard',
			{
				format: 'esm',
				name: 'metal-component',
				symbols: [
					'Component',
					'ComponentDataManager',
					'ComponentRegistry',
					'ComponentRenderer',
					'addListenersFromObj',
					'getComponentFn',
				],
			},
			'metal-debounce',
			{
				format: 'esm',
				name: 'metal-dom',
				symbols: [
					'DomEventEmitterProxy',
					'DomEventHandle',
					'addClasses',
					'append',
					'buildFragment',
					'closest',
					'contains',
					'customEvents',
					'delegate',
					'dom',
					'domData',
					'enterDocument',
					'exitDocument',
					'features',
					'globalEval',
					'globalEvalStyles',
					'hasClass',
					'isEmpty',
					'isNodeListLike',
					'match',
					'next',
					'on',
					'once',
					'parent',
					'prepend',
					'registerCustomEvent',
					'removeChildren',
					'removeClasses',
					'replace',
					'supportsEvent',
					'toElement',
					'toggleClasses',
					'triggerEvent',
				],
			},
			'metal-drag-drop',
			'metal-events',
			'metal-incremental-dom',
			'metal-jsx',
			'metal-key',
			'metal-keyboard-focus',
			'metal-multimap',
			'metal-pagination',
			'metal-path-parser',
			'metal-position',
			'metal-promise',
			'metal-router',
			'metal-scrollspy',
			'metal-soy',
			{name: 'metal-soy-bundle', symbols: []},
			'metal-state',
			'metal-storage',
			'metal-structs',
			'metal-throttle',
			'metal-toggler',
			'metal-uri',
			'metal-useragent',
			'metal-web-component',
			'querystring',
			'xss-filters',
		],
	},
};
