/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export enum DealRegistrationColumnKey {
	ACCOUNT_NAME = 'ACCOUNT-NAME',
	ADDITIONAL_CONTACTS = 'ADDITIONAL-CONTACTS',
	COUNTRY_CODE = 'COUNTRY-CODE',
	CURRENCY = 'CURRENCY',
	DATE_SUBMITTED = 'DATE_SUBMITTED',
	PARTNER_ACCOUNT_NAME = 'PARTNER-ACCOUNT-NAME',
	PARTNER_NAME = 'PARTNER-NAME',
	PRIMARY_PROSPECT_BUSINESS_UNIT = 'PRIMARY-PROSPECT-BUSINESS-UNIT',
	PRIMARY_PROSPECT_DEPARTMENT = 'PRIMARY-PROSPECT-DEPARTMENT',
	PRIMARY_PROSPECT_EMAIL = 'PRIMARY-PROSPECT-EMAIL',
	PRIMARY_PROSPECT_JOB_ROLE = 'PRIMARY-PROSPECT-JOB-ROLE',
	PRIMARY_PROSPECT_NAME = 'PRIMARY-PROSPECT-NAME',
	PRIMARY_PROSPECT_PHONE = 'PRIMARY-PROSPECT-PHONE',
	PROPECT_BUSINES_UNIT = 'PROPECT-BUSINES-UNIT',
	PROSPECT_ADDRESS = 'PROSPECT-ADDRESS',
	PROSPECT_CITY = 'PROSPECT-CITY',
	PROSPECT_COUNTRY = 'PROSPECT-COUNTRY',
	PROSPECT_DEPARTMENT = 'PROSPECT-DEPARTMENT',
	PROSPECT_EMAIL = 'PROSPECT-EMAIL',
	PROSPECT_INDUSTRY = 'PROSPECT-INDUSTRY',
	PROSPECT_JOB_ROLE = 'PROSPECT-JOB-ROLE',
	PROSPECT_POSTAL_CODE = 'PROSPECT-POSTAL-CODE',
	PROSPECT_STATE = 'PROSPECT-STATE',
	STATUS = 'STATUS',
	STATUS_DETAIL = 'STATUS_DETAIL',
	TYPE = 'TYPE',
}
