##
## Test Batch
##

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Liferay Learn Site Initializer") OR \
            (testray.main.component.name ~ "Liferay Learn Site Initializer")\
        )

##
## Testray
##

    testray.main.component.name=Liferay Learn Site Initializer