/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export declare enum TYPES {
	ADD_OBJECT_DEFINITION_TO_OBJECT_FOLDER = 'ADD_OBJECT_DEFINITION_TO_OBJECT_FOLDER',
	BULK_CHANGE_NODE_VIEW = 'BULK_CHANGE_NODE_VIEW',
	CHANGE_NODE_VIEW = 'CHANGE_NODE_VIEW',
	CREATE_MODEL_BUILDER_STRUCTURE = 'CREATE_MODEL_BUILDER_STRUCTURE',
	DELETE_OBJECT_DEFINITION = 'DELETE_OBJECT_DEFINITION',
	SET_ELEMENTS = 'SET_ELEMENTS',
	SET_LOADING_OBJECT_FOLDER = 'SET_LOADING_OBJECT_FOLDER',
	SET_OBJECT_FOLDER_NAME = 'SET_OBJECT_FOLDER_NAME',
	SET_SELECTED_OBJECT_DEFINITION_NODE = 'SET_SELECTED_OBJECT_DEFINITION_NODE',
	SET_SELECTED_OBJECT_RELATIONSHIP_EDGE = 'SET_SELECTED_OBJECT_RELATIONSHIP_EDGE',
	SET_SHOW_CHANGES_SAVED = 'SET_SHOW_CHANGES_SAVED',
	UPDATE_OBJECT_DEFINITION_NODE = 'UPDATE_OBJECT_DEFINITION_NODE',
}
