/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.ext.test.internal.portal.uuid;

import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.security.SecureRandomUtil;
import com.liferay.portal.uuid.PortalUUIDImpl;

import java.util.UUID;

/**
 * @author Victor Ware
 */
public class ExtPortalUUIDImpl extends PortalUUIDImpl {

	@Override
	public String generate() {
		UUID uuid = new UUID(
			SecureRandomUtil.nextLong(), SecureRandomUtil.nextLong());

		if (_log.isInfoEnabled()) {
			_log.info("UUID generated by ExtPortalUUIDImpl");
		}

		return uuid.toString();
	}

	private static final Log _log = LogFactoryUtil.getLog(
		ExtPortalUUIDImpl.class);

}